#!/usr/bin/env bash
# Displays "Best School" 10 times

#n=10
#for ((i=0 ; i<n ; i++));
#do
#	echo "Best School"
#done

#array=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" )
#for i in "${array[@]}";
#do
#	echo "$i"
#done

for _ in {1..10};
do
	echo "Best School"
done
