#!/usr/bin/env bash
# Displays 'Best School' 10 times using a while loop

counter=1
# while [[ "$counter" -le 10 ]]; do
#    echo "Best School"
#    counter=$((counter + 1))
# done

while ((counter <= 10)); do
    echo "Best School"
    ((counter++))
done
