#!/usr/bin/env bash

i=0

#while ((i < 10));
#do
#	echo "Best School"
#	if ((i == 8)); then
#		echo "Hi"
#	fi
#	((i++))
#done

while [[ $i -lt 10 ]];
do
	echo "Best School"
	if [[ $i == 8 ]]; then
		echo "Hi"
	fi
	((i++))
done
