#!/usr/bin/env bash
# use of case statement

i=1
while [[ "$i" -le 20 ]]; do
    case "$i" in
        4)
	    echo "$i"
            echo "bad luck from China"
            ;;
        9)
	    echo "$i"
            echo "bad luck from China"
            ;;
        17)
	    echo "$i"
            echo "bad luck from China"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done 
